name: Build latest
on:
  schedule:
    - cron: '0 22 2 * *'
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (amd64)
        uses: docker/build-push-action@v2
        with:
          build-arg:
            - ARCH=x86_64
          context: .
          platform: linux/amd64
          push: true
          tags: |
            paperist/alpine-texlive-ja:${{ steps.extract_tag_name.outputs.tag }}
            ghcr.io/paperist/alpine-texlive-ja:${{ steps.extract_tag_name.outputs.tag }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-arg:
            - ARCH=aarch64
          context: .
          platform: linux/arm64
          push: true
          tags: |
            paperist/alpine-texlive-ja:${{ steps.extract_tag_name.outputs.tag }}
            ghcr.io/paperist/alpine-texlive-ja:${{ steps.extract_tag_name.outputs.tag }}
